removeTrailingWhitespace: 1 %Remove useless blank spaces.

indentAfterHeadings:
    part:
       indentAfterThisHeading: 1
       level: 1
    chapter:
       indentAfterThisHeading: 1
       level: 2
    section:
       indentAfterThisHeading: 1
       level: 3
    section*:
       indentAfterThisHeading: 1
       level: 3
    subsection:
       indentAfterThisHeading: 1
       level: 4
    subsection*:
       indentAfterThisHeading: 1
       level: 4

modifyLineBreaks:
  textWrapOptions:
    columns: 
    separator: ""
    perCodeBlockBasis: 0
    all: 0
    alignAtAmpersandTakesPriority: 1
    environments:
        quotation: 0
    ifElseFi: 0
    optionalArguments: 0
    mandatoryArguments: 0
    items: 0
    specialBeginEnd: 0
    afterHeading: 0
    preamble: 0
    filecontents: 0
    masterDocument: 0
