rm(list = ls());
cat("\014"); setwd("/Users/ema/github/data_aggregation")
library(data.table)
library(dplyr)
library(formattable)
library(tidyr)
library(xtable) 
library(stringi)

rank_table = read.csv("latex/tables/rank_table.txt")
print(xtable(rank_table, type = "latex"), file = "rank_table.tex", include.rownames=FALSE)
rank_table_latex = readLines("rank_table.tex")

rank_table_latex = gsub(pattern = "Jaccard", replace = "{\\\\color[HTML]{00D768}", x = rank_table_latex)
rank_table_latex = gsub(pattern = "REGE", replace = "{\\\\color[HTML]{EF2A00}", x = rank_table_latex)
rank_table_latex = gsub(pattern = "predator", replace = "{\\\\color[HTML]{0051D7}", x = rank_table_latex)
rank_table_latex = gsub(pattern = "prey", replace = "{\\\\color{orange}", x = rank_table_latex)
rank_table_latex = gsub(pattern = "groups", replace = "{\\\\color[HTML]{6200D7}", x = rank_table_latex)
rank_table_latex = gsub(pattern = "density", replace = "{\\\\color[HTML]{9B9B9B}", x = rank_table_latex)
rank_table_latex = gsub(pattern = "\\(", replace = "", x = rank_table_latex)
rank_table_latex = gsub(pattern = ")", replace = "}", x = rank_table_latex)
rank_table_latex = gsub(pattern = "First", replace = "C1", x = rank_table_latex)
rank_table_latex = gsub(pattern = "Second", replace = "C2", x = rank_table_latex)
rank_table_latex = gsub(pattern = "Third", replace = "C3", x = rank_table_latex)
rank_table_latex = gsub(pattern = "Fifth", replace = "C5", x = rank_table_latex)
rank_table_latex = gsub(pattern = "Fourth", replace = "C4", x = rank_table_latex)
rank_table_latex = gsub(pattern = "Sixth", replace = "C6", x = rank_table_latex)

write(rank_table_latex, file = "latex/tables/rank_table.tex")